### ISSUE TITLE
Errore con ipython in congruence.py

### ISSUE THREAD

**Issue by ToloCops** [filp8/gauss_elimination#29]
Quando viene chiamata multiplyTableCongruence(generatoreR(1,9),9,moltiplicazione) all'interno dello script da la matrice corretta ma quano viene chiamata in ipython da la stessa matrice ma moltiplicata 4 volte

**- Screenshot con sopra ipython e sotto run dello script:**

<img width="658" alt="Screenshot 2024-01-11 alle 11 16 30" src="https://github.com/filp8/gauss_elimination/assets/72523234/d7cfd104-7511-4c34-9c1f-9bded6d3b303">

**Comment by LucaSforza** [comment]
Ho trovato il bug! Non è un problema di ipython, ma è un problema della funzione `generatore` in `congruence.py` dove come parametro di default una lista. In python questa cosa non va mai fatta perché si creano bug strani per via di come sono implementati i parametri di default in python.
In poche parole quando modifichi quella lista di default essa rimane invariata anche alla prossima esecuzione, infatti se provi a chiamare più volte quella funzione (anche fuori da ipython) vedrai che escono cose strane.

Per maggiori informazioni su questo argomento leggi [qua](https://stackoverflow.com/questions/18141652/python-function-with-default-list-argument)

**Comment by LucaSforza** [comment]
Grazie a [questo](https://github.com/filp8/gauss_elimination/pull/27/commits/4fb965a07e086ade2a4ed6077b869b0e1c25137f) commit il bug è stato risolto
