### ISSUE TITLE
Cast forzato nella funzione dot_product

### ISSUE THREAD

**Issue by ToloCops** [filp8/gauss_elimination#35]
#33 
Nonostante in **dot_product** abbiamo specificato il tipo degli argomenti, come scalar continua ad accettare anche valori non di tipo diverso da **Fraction**, rendendo necessario il cast forzato del valore di scalar all'interno del body.

**- Debug screenshot:**

<img width="1088" alt="Screenshot 2024-01-12 alle 17 43 05" src="https://github.com/filp8/gauss_elimination/assets/72523234/d40a234a-f1e1-4906-b29e-604eb45a789d">

**Comment by LucaSforza** [comment]
Non riesco a riprodurre il bug, mi puoi dire esattamente quali erano gli input che hai fatto in gauss?

**Comment by ToloCops** [comment]
il bug si può vedere solo facendo il debug, guardando il valore della variabile scalar, che all'inizio della funzione è un double ma poi lo abbiamo castato a Fraction. Il programma quindi non da errori, ma andrebbe trovato un modo più pulito per risolverlo. Inoltre non importa quali siano gli input.

**Comment by coding-samu** [comment]
Sembrerebbe che il problema nasca dal fatto che la matrice che viene passata nel main non è una matrice di Fraction. 

Ho notato come il metodo input_matrix() nel file tui chiamato dal main restituisce una matrice di interi e non una matrice di Fraction, potrebbe essere quindi questa la causa del problema.
![image](https://github.com/filp8/gauss_elimination/assets/80750844/b7357593-e43a-467b-a4de-d0d2dca301f6)

Probabilmente Luca non riscontra questo problema (se sta utilizzando le matrici dei test) perché sono già convertite nel giusto tipo 
![image](https://github.com/filp8/gauss_elimination/assets/80750844/51b48426-4461-4f29-a73f-c30990125cb6)

Ho creato un nuovo branch in cui ho implementato le modifiche

**Comment by ToloCops** [comment]
me sa che c'hai raggio, comunque il codice sembra top

**Comment by LucaSforza** [comment]
Ho mergiato la pull request #37 quindi penso che vada bene, comunque in python quando ci sta un problema dei tipi è solo un problema relativo poiché a python importa poco dei tipi. Ma grazie a #37 il problema che c'era è stato risolto
